=== BackupTheBerlios/harvestman/HarvestMan/HarvestMan/tools/HarvestMan.dtd
<?xml version="1.0" encoding="utf-8"?>
<!--- Document type definition for HarvestMan -->
<!ELEMENT HarvestMan
	(config) >
<!ELEMENT config (project, network, download, control, system, files, indexer, display)>
<!ELEMENT project (url, name, basedir, verbosity, timeout)>
<!ELEMENT url (EMPTY)>
<!ELEMENT name (EMPTY)>
<!ELEMENT basedir (EMPTY)>
<!ELEMENT verbosity (EMPTY)>
<!ELEMENT timeout (EMPTY)>

<!ELEMENT network (proxy, urlserver)>
<!ELEMENT proxy (proxyserver, proxyuser, proxypasswd, proxyport)>
<!ELEMENT proxyserver (EMPTY)>
<!ELEMENT proxyuser (EMPTY)>
<!ELEMENT proxypasswd (EMPTY)>
<!ELEMENT proxyport (EMPTY)>

<!ELEMENT urlserver (urlhost, urlport)>
<!ELEMENT urlhost (EMPTY)>
<!ELEMENT urlport (EMPTY)>

<!ELEMENT download (types, cache, misc)>
<!ELEMENT types (html, images, javascript, javaapplet, forms, cookies)>
<!ELEMENT html (EMPTY)>
<!ELEMENT images (EMPTY)>
<!ELEMENT javascript (EMPTY)>
<!ELEMENT javaapplet (EMPTY)>
<!ELEMENT forms (EMPTY)>
<!ELEMENT cookies (EMPTY)>

<!ELEMENT cache (datacache)>
<!ELEMENT datacache (EMPTY)>

<!ELEMENT misc (retries, tidyhtml)>
<!ELEMENT retries (EMPTY)>
<!ELEMENT tidyhtml (EMPTY)>

<!ELEMENT control (links, extent, limits, rules, filters)>
<!ELEMENT links (imagelinks, stylesheetlinks)>
<!ELEMENT imagelinks (EMPTY)>
<!ELEMENT stylesheetlinks (EMPTY)>

<!ELEMENT extent (fetchlevel, extserverlinks, extpagelinks, depth, extdepth, subdomain)>
<!ELEMENT fetchlevel (EMTPY)>
<!ELEMENT extserverlinks (EMTPY)>
<!ELEMENT extpagelinks (EMTPY)>
<!ELEMENT depth (EMTPY)>
<!ELEMENT extdepth (EMTPY)>
<!ELEMENT subdomain (EMTPY)>

<!ELEMENT limits (maxextservers, maxextdirs, maxfiles, maxfilesize, connections, requests, timelimit)>
<!ELEMENT maxextservers (EMPTY)>
<!ELEMENT maxextdirs (EMPTY)>
<!ELEMENT maxfiles (EMPTY)>
<!ELEMENT maxfilesize (EMPTY)>
<!ELEMENT connections (EMPTY)>
<!ELEMENT requests (EMPTY)>
<!ELEMENT timelimit (EMPTY)>

<!ELEMENT rules (robots, urlpriority, serverpriority)>
<!ELEMENT robots (EMPTY)>
<!ELEMENT urlpriority (EMPTY)>
<!ELEMENT serverpriority (EMPTY)>

<!ELEMENT filters (urlfilter, serverfilter, wordfilter, junkfilter)>
<!ELEMENT urlfilter (EMPTY)>
<!ELEMENT serverfilter (EMPTY)>
<!ELEMENT wordfilter (EMPTY)>
<!ELEMENT junkfilter (EMPTY)>

<!ELEMENT system (workers, trackers, locale, fastmode)>
<!ELEMENT workers (EMPTY)>
<!ELEMENT trackers (EMPTY)>
<!ELEMENT locale (EMPTY)>
<!ELEMENT fastmode (EMPTY)>

<!ELEMENT files (urllistfile, urltreefile)>
<!ELEMENT urllistfile (EMPTY)>
<!ELEMENT urltreefile (EMPTY)>

<!ELEMENT indexer (localise)>
<!ELEMENT localise (EMPTY)>

<!ELEMENT display (browsepage)>
<!ELEMENT browsepage (EMPTY)>

<!ATTLIST config version CDATA "3.0">
<!ATTLIST config xmlversion CDATA "1.0">
<!ATTLIST verbosity value CDATA "3">
<!ATTLIST timeout value CDATA "600.0">
<!ATTLIST proxyport value CDATA "80">
<!ATTLIST urlserver status CDATA "0">
<!ATTLIST urlport value CDATA "3081">
<!ATTLIST html value CDATA "1">
<!ATTLIST images value CDATA "1">
<!ATTLIST javascript value CDATA "1">
<!ATTLIST javaapplet value CDATA "1">
<!ATTLIST forms value CDATA "0">
<!ATTLIST cookies value CDATA "1">
<!ATTLIST cache status CDATA "1">
<!ATTLIST datacache value CDATA "1">
<!ATTLIST retries value CDATA "1">
<!ATTLIST tidyhtml value CDATA "1">
<!ATTLIST imagelinks value CDATA "1">
<!ATTLIST stylesheetlinks value CDATA "1">
<!ATTLIST fetchlevel value CDATA "0">
<!ATTLIST extserverlinks value CDATA "0">
<!ATTLIST extpagelinks value CDATA "1">
<!ATTLIST depth value CDATA "0">
<!ATTLIST extdepth value CDATA "0">
<!ATTLIST subdomain value CDATA "0">
<!ATTLIST maxextservers value CDATA "0">
<!ATTLIST maxextdirs value CDATA "0">
<!ATTLIST maxfiles value CDATA "5000">
<!ATTLIST maxfilesize value CDATA "1048576">
<!ATTLIST connections value CDATA "5">
<!ATTLIST requests value CDATA "5">
<!ATTLIST timelimit value CDATA "-1">
<!ATTLIST junkfilter value CDATA "0">
<!ATTLIST workers status CDATA "1">
<!ATTLIST workers size CDATA "10">
<!ATTLIST workers timeout CDATA "200">
<!ATTLIST trackers value CDATA "4">
<!ATTLIST fastmode value CDATA "1">

<!ATTLIST localise value CDATA "2">

<!ATTLIST browsepage value CDATA "1">

=== BackupTheBerlios/harvestman/HarvestMan/HarvestMan/tools/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE HarvestMan SYSTEM "HarvestMan.dtd">
<HarvestMan>
	<config version="3.0" xmlversion="1.0">

		<project>
			<url>www.python.org/doc/current/tut/tut.html</url>
			<name>pytut</name>
			<basedir>~/websites</basedir>
			<verbosity value="2"/>
			<timeout value="300.0"/>
		</project>

		<network>
			<proxy>
				<proxyserver></proxyserver>
				<proxyuser></proxyuser>
				<proxypasswd></proxypasswd>
				<proxyport value="0"/>
			</proxy>
			<urlserver status="0">
				<urlhost>localhost</urlhost>
				<urlport value="3081"/>
			</urlserver>
		</network>

		<download>
			<types>
				<html value="1"/>
				<images value="1"/>
				<javascript value="1"/>
				<javaapplet value="1"/>
				<forms value="1"/>
				<cookies value="1"/>
			</types>
			<cache status="1">
				<datacache value="1"/>
			</cache>
			<misc>
				<retries value="1"/>
				<tidyhtml value="0"/>
			</misc>
		</download>

		<control>
			<links>
				<imagelinks value="1"/>
				<stylesheetlinks value="1"/>
			</links>
			<extent>
				<fetchlevel value="0"/>
				<extserverlinks value="0"/>
				<extpagelinks value="1"/>
				<depth value="10"/>
				<extdepth value="0"/>
				<subdomain value="0"/>
			</extent>
			<limits>
				<maxextservers value="0"/>
				<maxextdirs value="0"/>
				<maxfiles value="5000"/>
				<maxfilesize value="1048576"/>
				<connections value="5"/>
				<requests value="5"/>
				<timelimit value="-1"/>
			</limits>
			<rules>
				<robots value="1"/>
				<urlpriority></urlpriority>
				<serverpriority></serverpriority>
			</rules>
			<filters>
				<urlfilter></urlfilter>
				<serverfilter></serverfilter>
				<wordfilter></wordfilter>
				<junkfilter value="1"/>
			</filters>
		</control>

		<system>
			<workers status="1" size="10" timeout="200.0"/>
			<trackers value="4"/>
			<locale>american</locale>
			<fastmode value="1"/>
		</system>

		<files>
			<urllistfile></urllistfile>
			<urltreefile></urltreefile>
		</files>

		<indexer>
			<localise value="2"/>
		</indexer>
		<display>
			<browsepage value="1"/>
		</display>

	</config>

</HarvestMan>
